version: '3.1'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fxdeals
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=toluwase

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toluwase
      - POSTGRES_DATABASE=fxdeals
    ports:
      - "5438:5432"